### ISSUE TITLE
Cryptocurrency module

### ISSUE THREAD

**Issue by alvinjoelsantos** [alvinjoelsantos/marketo#1]
Fork [Fixer.io currency module](https://github.com/thirtybees/fixerio/tree/5a1b53067830b1adb7806338b820a7fdc66a4670) and modify it to call [CryptoCompare API](https://www.cryptocompare.com/api/)

Pairs:

- XMR/USD
- XMR/EUR
- XMR/BTC
- BTC/USD
- BTC/EUR

**Comment by serhack** [comment]
This will be the first part of my job!
